require "faker"

  User.create(
  first_name: "Chinmay", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "kamble@lol.com", 
  url1: "https://picsum.photos/200/300?grayscale", 
  about: "CODE CLUB REPRESENTATIVE",
  password: "123456",   
  password_confirmation: "123456")

  User.create(
    first_name: "Atharva", 
    dob_day: Faker::Number.within(range: 1..30), 
    dob_month: Faker::Number.within(range: 1..12), 
    dob_year: Faker::Number.within(range: 1980..2000), 
    show_gender: Faker::Boolean.boolean, 
    gender_identity: "man", 
    show_sexual_orientation: Faker::Boolean.boolean,
    sexual_orientation: "straight",
    gender_interest: "woman", 
    email: "atharva@lol.com", 
    url1: "https://picsum.photos/200/300?grayscale", 
    about: "Only API BAAMZI",
    password: "123456",   
    password_confirmation: "123456")

    User.create(
      first_name: "Nakul", 
      dob_day: Faker::Number.within(range: 1..30), 
      dob_month: Faker::Number.within(range: 1..12), 
      dob_year: Faker::Number.within(range: 1980..2000), 
      show_gender: Faker::Boolean.boolean, 
      gender_identity: "man", 
      show_sexual_orientation: Faker::Boolean.boolean,
      sexual_orientation: "straight",
      gender_interest: "woman", 
      email: "nakul@lol.com", 
      url1: "https://picsum.photos/200/300?grayscale", 
      about: "ROR GUY",
      password: "123456",   
      password_confirmation: "123456")

      User.create(
        first_name: "Ashish", 
        dob_day: Faker::Number.within(range: 1..30), 
        dob_month: Faker::Number.within(range: 1..12), 
        dob_year: Faker::Number.within(range: 1980..2000), 
        show_gender: Faker::Boolean.boolean, 
        gender_identity: "man", 
        show_sexual_orientation: Faker::Boolean.boolean,
        sexual_orientation: "straight",
        gender_interest: "woman", 
        email: "Ashish@lol.com", 
        url1: "https://picsum.photos/200/300?grayscale", 
        about: "BROOKIE looking to make money",
        password: "123456",   
        password_confirmation: "123456")

        User.create(
          first_name: "Aishwarya", 
          dob_day: Faker::Number.within(range: 1..30), 
          dob_month: Faker::Number.within(range: 1..12), 
          dob_year: Faker::Number.within(range: 1980..2000), 
          show_gender: Faker::Boolean.boolean, 
          gender_identity: "women", 
          show_sexual_orientation: Faker::Boolean.boolean,
          sexual_orientation: "straight",
          gender_interest: "woman", 
          email: "aish@lol.com", 
          url1: "https://picsum.photos/200/300?grayscale", 
          about: "CAT LOVER",
          password: "123456",   
          password_confirmation: "123456")

          User.create(
            first_name: "kyle", 
            dob_day: Faker::Number.within(range: 1..30), 
            dob_month: Faker::Number.within(range: 1..12), 
            dob_year: Faker::Number.within(range: 1980..2000), 
            show_gender: Faker::Boolean.boolean, 
            gender_identity: "women", 
            show_sexual_orientation: Faker::Boolean.boolean,
            sexual_orientation: "straight",
            gender_interest: "woman", 
            email: "kyle@lol.com", 
            url1: "https://picsum.photos/200/300?grayscale", 
            about: "DOG lover",
            password: "123456",   
            password_confirmation: "123456")
            User.create(
              first_name: "EXample man 1", 
              dob_day: Faker::Number.within(range: 1..30), 
              dob_month: Faker::Number.within(range: 1..12), 
              dob_year: Faker::Number.within(range: 1980..2000), 
              show_gender: Faker::Boolean.boolean, 
              gender_identity: "man", 
              show_sexual_orientation: Faker::Boolean.boolean,
              sexual_orientation: "straight",
              gender_interest: "woman", 
              email: "example man@lol.com", 
              url1: "https://picsum.photos/200/300?grayscale", 
              about: "GYMBRO",
              password: "123456",   
              password_confirmation: "123456")

              User.create(
                first_name: "Ajinkya", 
                dob_day: Faker::Number.within(range: 1..30), 
                dob_month: Faker::Number.within(range: 1..12), 
                dob_year: Faker::Number.within(range: 1980..2000), 
                show_gender: Faker::Boolean.boolean, 
                gender_identity: "man", 
                show_sexual_orientation: Faker::Boolean.boolean,
                sexual_orientation: "straight",
                gender_interest: "woman", 
                email: "hinde@lol.com", 
                url1: "https://picsum.photos/200/300?grayscale", 
                about: "HTML TOPPER",
                password: "123456",   
                password_confirmation: "123456")

                User.create(
                  first_name: "Jeetesh", 
                  dob_day: Faker::Number.within(range: 1..30), 
                  dob_month: Faker::Number.within(range: 1..12), 
                  dob_year: Faker::Number.within(range: 1980..2000), 
                  show_gender: Faker::Boolean.boolean, 
                  gender_identity: "man", 
                  show_sexual_orientation: Faker::Boolean.boolean,
                  sexual_orientation: "straight",
                  gender_interest: "woman", 
                  email: "jeet@lol.com", 
                  url1: "https://picsum.photos/200/300?grayscale", 
                  about: "NPM NERD",
                  password: "123456",   
                  password_confirmation: "123456")

                  User.create(
                    first_name: "Champ", 
                    dob_day: Faker::Number.within(range: 1..30), 
                    dob_month: Faker::Number.within(range: 1..12), 
                    dob_year: Faker::Number.within(range: 1980..2000), 
                    show_gender: Faker::Boolean.boolean, 
                    gender_identity: "man", 
                    show_sexual_orientation: Faker::Boolean.boolean,
                    sexual_orientation: "straight",
                    gender_interest: "woman", 
                    email: "cham@lol.com", 
                    url1: "https://picsum.photos/200/300?grayscale", 
                    about: "UI/UX is love",
                    password: "123456",   
                    password_confirmation: "123456")

                    User.create(
                      first_name: "Jay", 
                      dob_day: Faker::Number.within(range: 1..30), 
                      dob_month: Faker::Number.within(range: 1..12), 
                      dob_year: Faker::Number.within(range: 1980..2000), 
                      show_gender: Faker::Boolean.boolean, 
                      gender_identity: "man", 
                      show_sexual_orientation: Faker::Boolean.boolean,
                      sexual_orientation: "straight",
                      gender_interest: "man", 
                      email: "jay@lol.com", 
                      url1: "https://picsum.photos/200/300?grayscale", 
                      about: "WEB 3.0 guy",
                      password: "123456",   
                      password_confirmation: "123456")